### ISSUE TITLE
Observer not removed

### ISSUE THREAD

**Issue by MihaMajcen** [picciano/iOS-Tone-Generator#4]
You should add 
[[NSNotificationCenter defaultCenter] removeObserver:self];
into dealloc method, otherwise it will crash when interruption notification will be posted (incomming call).

**Comment by picciano** [comment]
Good catch, thanks.

**Comment by phaphan** [comment]
Thank you. To elaborate, it seems tat the application will crash when entering the foreground after an interruption has occurred when the application was sent to the background. Removing the observer in the dealloc mehod certainly solved this issue.
